---
title: "Pre-Testing"
author: "Gustav Pirich"
date: '2024-12-04'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# =============================================================================
# Load Libraries
# =============================================================================
# Install necessary libraries if not already installed
pacman::p_load(tidyverse, here, hmisc, reshape2, stargazer, tidyr)


```


```{r, include=FALSE}
survey <- read.csv("C:\\Users\\GustavPirich\\Dropbox\\climate_nature_narratives\\input\\rawdata\\experiment\\pretest\\climate_change_narratives_November+29,+2024_01.40.csv")

# storing the second row as subheaders toc check up 
#subheaders <- c(survey[1:2, ])
#subheaders$Q0


# =============================================================================
# Data Cleaning and Merging
# =============================================================================

# Process the data
df_cleaned <- survey %>%
  slice(-1) %>%
  mutate(across(where(is.character), as.character))

# Remove the second row from the dataframe
df_cleaned_1 <- df_cleaned[-2, ]

df_cleaned_3 <- df_cleaned_1 %>%
  slice(-c(1:7)) %>%
  mutate(treatment = ifelse(FL_6_DO == "Treatment", 1, 0))


#Define the lists of adjectives for each classification
hero_adjectives <- c("good", "trustworthy", "reliable", "innovative", "useful", "dependable")
villain_adjectives <- c("bad", "threatening", "harmful", "dangerous", "unreliable", "greedy")
victim_adjectives <- c("vulnerable", "exploited", "afflicted", "weak", "naive", "powerless")

# Create the new columns
df_cleaned_3$hero <- sapply(df_cleaned_3$Q6, function(x) sum(trimws(unlist(strsplit(x, ","))) %in% hero_adjectives))
df_cleaned_3$villain <- sapply(df_cleaned_3$Q6, function(x) sum(trimws(unlist(strsplit(x, ","))) %in% villain_adjectives))
df_cleaned_3$victim <- sapply(df_cleaned_3$Q6, function(x) sum(trimws(unlist(strsplit(x, ","))) %in% victim_adjectives))

# Create the dummy variable columns
df_cleaned_3$hero_dummy <- ifelse(df_cleaned_3$hero > 0, 1, 0)
df_cleaned_3$villain_dummy <- ifelse(df_cleaned_3$villain > 0, 1, 0)
df_cleaned_3$victim_dummy <- ifelse(df_cleaned_3$victim > 0, 1, 0)


```

